// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuE1tpboamV5lpdQlYW10Y0_65Q3n39Ls',
    appId: '1:544236174683:web:cde219bb35e120fab86e7e',
    messagingSenderId: '544236174683',
    projectId: 'ecommerce-ae543',
    authDomain: 'ecommerce-ae543.firebaseapp.com',
    storageBucket: 'ecommerce-ae543.firebasestorage.app',
    measurementId: 'G-XQ5QBRGETQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASJG7SI0jgYjcCX849R0ZEN7GMeKtiO4',
    appId: '1:544236174683:android:787493041f8952d7b86e7e',
    messagingSenderId: '544236174683',
    projectId: 'ecommerce-ae543',
    storageBucket: 'ecommerce-ae543.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDs6C7-0acmVNtpze-dVEKSBR-ADO3Pg4',
    appId: '1:544236174683:ios:a449fc4085dcab21b86e7e',
    messagingSenderId: '544236174683',
    projectId: 'ecommerce-ae543',
    storageBucket: 'ecommerce-ae543.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTCz5FmXktytmkqE9tH9afp3M3tNs-Tnc',
    appId: '1:295858621744:ios:385a4f4908012be189ccf5',
    messagingSenderId: '295858621744',
    projectId: 'ecommerce-3f6a3',
    storageBucket: 'ecommerce-3f6a3.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjrENPYUbVktGBnKTtxLVfiklaih3FnaQ',
    appId: '1:295858621744:web:6edbb2290ef42fd289ccf5',
    messagingSenderId: '295858621744',
    projectId: 'ecommerce-3f6a3',
    authDomain: 'ecommerce-3f6a3.firebaseapp.com',
    storageBucket: 'ecommerce-3f6a3.firebasestorage.app',
    measurementId: 'G-W50159CN5H',
  );

}